name: CI Front-End

on:
  push:
    branches: [main]

jobs:
  verificacao:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código
        uses: actions/checkout@v4

      - name: Verificar arquivos
        run: |
          test -f index.html
          test -f style.css
